### ISSUE TITLE
Counterintuitive and unuseful results when attempting to edit a symlink

### ISSUE THREAD

**Issue by sobjornstad** [jwodder/inplace#2]
I tried doing an in-place edit on a symbolic link `foo.txt` in the current directory, requesting a backup copy with an extension of `~`.

**Expected result of an “in-place edit”**: A backup copy of the file, `foo.txt~`, is made either in the current directory or next to the destination file (I think you could argue for either behavior). The destination file pointed to by the symlink `foo.txt` is updated.

**Actual result**: A new file `foo.txt` is created next to the symlink, with the updates. The backup file `foo.txt~` is now a symlink to the destination. The destination file is unchanged.

Though the semantic meaning of dealing with symlinks can get complicated at times, I can't think of any situation in which this would be the desired behavior.

**Comment by sobjornstad** [comment]
(Calling this out of scope for this module is perfectly reasonable, but I thought you should at least be aware of it.)

**Comment by jwodder** [comment]
Handling of symlinks has now been changed in version 0.3.0: Now, if `in_place` is asked to operate on a symlink `link.txt` that points to `realfile.txt`, it will act as though it was asked to operate on `realfile.txt` instead, and the path `link.txt` will only be used when combining with `backup_ext` to construct a backup file path.
