### ISSUE TITLE
Write back regularly

### ISSUE THREAD

**Issue by ThomDietrich** [jwodder/inplace#3]
Hey there,
how is your package supposed to work with big files and interruptions?

I want to build a script that can process a big text file line by line.
As the process may take quite long, the script should allow to be terminated, resulting in a partly modified file the script later can continue with. Any ideas? Best!

**Comment by jwodder** [comment]
`in_place` works by writing to a temporary file that is then moved into place upon closing.  Because a new temporary file is opened each time, it won't resume writing to the same file after a restart, so I'm afraid it won't really help with your use case.

**Comment by ThomDietrich** [comment]
It occurred to me that I could use http://docs.python.org/library/signal.html to catch the interrupt and write all remaining lines to the temporary file. Anyhow, I already chose another path. Thanks for your answer!
